services:
  database:
    image: mysql:9
    restart: always
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - warehouse:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  warehouse: